# Generated by Django 2.2.24 on 2024-02-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
