# Generated by Django 2.2.24 on 2024-02-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20240213_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='categories/')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('customer_group', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('company_Name', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=50)),
                ('biller', models.CharField(choices=[('Test Biller', 'Test Biller')], max_length=50)),
                ('order_tax', models.CharField(blank=True, choices=[('No Text', 'No Text'), ('GST @5%', 'GST @5%'), ('VAT @10%', 'VAT @10%')], max_length=50, null=True)),
                ('order_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attach_document', models.FileField(blank=True, null=True, upload_to='sales/documents/')),
                ('sale_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Due', 'Due'), ('Paid', 'Paid')], max_length=50)),
                ('sale_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ManyToManyField(to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('biller', models.CharField(choices=[('Test Biller', 'Test Biller')], max_length=50)),
                ('order_tax', models.CharField(choices=[('No Text', 'No Text'), ('GST @5%', 'GST @5%'), ('VAT @10%', 'VAT @10%')], max_length=50)),
                ('order_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=5)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('return_note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=255)),
                ('received', models.BooleanField(default=False)),
                ('order_tax', models.CharField(max_length=255)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email Address')),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('combo', 'Combo'), ('digital', 'Digital'), ('service', 'Service')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('barcode_symbology', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_method', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='products/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CustomerOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='details',
            field=models.ManyToManyField(through='dashboard.OrderDetails', to='dashboard.Product'),
        ),
    ]
